name: mysql

services:
  db:
    image: mysql:8.0
    platform: linux/amd64 # Important for Apple Silicon (M1/M2)
    container_name: mysql_easytrade
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easytrade
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: phpmyadmin_easytrade
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
